config/routes.rb
Rails.application.routes.draw do
  namespace :rain do
    root :to => 'admin#index', as: 'root'
    get 'admin/rapids' => 'admin#rapids', :as => 'admin_rapids'
    get 'admin/drops' => 'admin#drops', :as => 'admin_drops'
    resources :drops

    resources :rapids, :except => [:show]

    constraints :format => 'js' do
      get 'javascripts/rain.js' => 'javascripts#cloud', :as => 'cloud_js'
    end
  end

  # get '/*id' => 'rain/drops#cloud', :as => 'clouds'
end

app/models/rain/cloud.rb
module Rain
  class Cloud < Drop
    def to_s
      name
    end
    alias :uri :to_s
  end
end

app/models/rain/drop.rb
module Rain
  class Drop < ActiveRecord::Base
    scope :drops, -> { where('type != ?', 'Rain::Cloud') }
    scope :clouds, -> { where('type = ?', 'Rain::Cloud') }

    validates_presence_of :name
    validates_uniqueness_of :name, :scope => :type

    alias :uri :to_s
    
    def uri=(new_uri)
      self.name = new_uri
    end
  
    def to_s
      name
    end
  end
end

app/models/rain/rapid.rb
module Rain
  class Rapid < ActiveRecord::Base
    has_many :rapids, :class_name => "Rain::Rapid", :foreign_key => "parent_id"
    belongs_to :rapid, :foreign_key => "id", :class_name => "Rain::Rapid"

    scope :root, -> { where(:parent_id => nil).order(:position) }
  
    def to_s
      name
    end
  end
end

app/controllers/rain/admin_controller.rb
class Rain::AdminController < ApplicationController
  before_filter :require_admin
  before_filter :rain_crumbs
  
  def index
  end
  
  def drops
    @drops = Rain::Drop.where(:type => nil).order(:name)
    @clouds = Rain::Cloud.order(:name)
  end
  
  def rapids
    @rapids = Rain::Rapid.root
  end

  private

  def rain_crumbs
    add_crumb 'Admin', '/admin'
    if action_name == 'index'
      add_crumb 'Rain'
    else
      add_crumb 'Rain', rain_root_path
      add_crumb action_name.titleize
    end
  end
end

app/controllers/rain/drops_controller.rb
class Rain::DropsController < ApplicationController
  include RainCmsHelper
  
  before_action :drop, :except => [:create]
  before_action :track_referrer, :only => [:cloud]
  before_action :check_permissions, :except => [:cloud]
  skip_before_action :authenticate, :only => [:cloud]
  before_action :authenticate_lite, :only => [:cloud]
  
  def check_permissions    
    return true if can_edit_drop?(params[:id].to_i)
    return require_admin
  end
  
  def new
    @back = params[:back]
    render 'rain/drops/new'
  end
  
  def edit
    @back = params[:back]
    render 'rain/drops/edit'
  end
  
  def show
    @back = params[:back]
    render 'rain/drops/new' and return if @drop.new_record?
    render 'rain/drops/edit'
  end
  
  def create
    if params[:rain_drop]
      @drop = Rain::Drop.new(params[:rain_drop])
    else
      @drop = Rain::Cloud.new(params[:rain_cloud])
    end
    respond_to do |format|
      if @drop.save
        flash[:success]= t(:drop_created)
        format.html { redirect_to(params[:back] || root_path) }
        format.xml  { render :xml => @drop, :status => :created, :location => @drop }
        format.js   { render 'rain/drops/update', :layout=>false}
      else
        format.html { render :new }
        format.xml  { render :xml => @drop.errors, :status => :unprocessable_entity }
        format.js   { render :text =>@drop.errors.inspect}
      end
    end
  end
  
  def update
    respond_to do |format|
      params.permit!
      if @drop.update_attributes(params[:rain_drop] || params[:rain_cloud])
        flash[:success] = t(:drop_updated)
        format.html { redirect_to(params[:back] || root_path) }
        format.xml  { head :ok }
        format.js   { render 'rain/drops/update', :layout=>false}
      else
        format.html { render :action => "edit", :layout=>false }
        format.xml  { render :xml => @drop.errors, :status => :unprocessable_entity }
        format.js   { render :text =>@drop.errors.inspect}
      end
    end
  end
  
  def destroy
    @drop.delete
    
    redirect_to rain_admin_drops_path
  end

  def cloud
    raise ActionController::RoutingError.new("Rain was unable to find #{request.path}") unless request.format == 'text/html'
    build_crumbs

    if (@drop.admin_only? && !is_admin?) || (@drop.user_only? && !logged_in?)
      flash[:error] = "You are not authorized to view this page"
      redirect_to '/'
    end

    if @drop.new_record? && !is_admin?
      raise ActionController::RoutingError.new("Rain was unable to find #{request.path}")
    end
    render 'rain/clouds/_cloud', :locals=>{:cloud=>@drop}, :layout => request.xhr? ? '' : @drop.layout
  end
  
  private  
    def drop
      if params[:id].match(/\/edit$/)
        params[:id] = params[:id][0..-6]
        force_edit = true
      end

      name = (params[:id].is_a?(Array) ? params[:id].join('/') : params[:id]).downcase
      if name.to_i > 0
        @drop ||= Rain::Drop.find(params[:id])
      else
        if action_name == 'cloud'
          @drop ||= Rain::Cloud.find_by_name(name) || Rain::Cloud.new(:name=>name)
        else
          @drop ||= Rain::Drop.find_by_name(name) || Rain::Drop.create(:name=>name)
        end
      end

      return edit if force_edit
    end
        
    def track_referrer
      session[:rain_referrer] = request.referer
    end

    def build_crumbs
      uri = request.path
      search_path = ""
      crumbs = uri.split('/').reject{|u| u.blank?}
      crumbs.pop

      if crumbs.length
        crumbs.each do |c|
          if cloud = Rain::Cloud.find_by_name(search_path + c)
            add_crumb cloud.title, "/#{cloud.name}"
            search_path += "#{c}/"
          end
        end
      end
      add_crumb @drop.title
    end
end

app/controllers/rain/rapids_controller.rb
class Rain::RapidsController < ApplicationController
  before_filter :require_admin
  
  def new
    @rapid = Rain::Rapid.new
  end
  
  def edit
    @rapid = Rain::Rapid.find(params[:id])
    
  end
  
  def create
     @rapid = Rain::Rapid.new(params[:rain_rapid])
     respond_to do |format|
       if @rapid.save
         flash[:success]= t(:drop_created)
         format.html { redirect_to :rain_admin_rapids}
         format.xml  { render :xml => @rapid, :status => :created, :location => @drop }
       else
         format.html { render :new }
         format.xml  { render :xml => @rapid.errors, :status => :unprocessable_entity }
       end
     end
   end
   
   def update
     @rapid = Rain::Rapid.find(params[:id])
     
     respond_to do |format|
       if @rapid.update_attributes(params[:rain_rapid])
         flash[:success] = t(:rapid_updated)
         format.html { redirect_to :rain_admin_rapids}
         format.xml  { head :ok }
       else
         format.html { render :action => "edit", :layout=>false }
         format.xml  { render :xml => @rapid.errors, :status => :unprocessable_entity }
       end
     end
   end
   
   def destroy
     @rapid = Rain::Rapid.find(params[:id])
     @rapid.delete

     redirect_to :rain_admin_rapids
   end
end

app/views/rain/drops/_drop.html.erb
<div class="rain_drop <%= drop.id %>">

  <%= raw drop.content %>
  
  <% if can_edit_drop?(drop.id) %>
    [<%= link_to "Edit", edit_rain_drop_path(drop, {back: request.url}), :class=>"drop-edit edit" %>]
  <% end %>
</div>

app/views/rain/drops/_form.html.erb
<%= form_for form, :url => (form.new_record? ? rain_drops_path(form) : rain_drop_path(form)), :html=>{:id=>"edit_#{form.name}_form"} do |f| %>
  <%= f.hidden_field :name %>
  <input type="hidden" name="back" value="<%= @back %>">
  <% if f.object.type == 'Rain::Cloud' %>    
    <%= f.label :title %>
    <%= f.text_field :title%>
    <%= f.check_box :show_title %> <%= f.label :show_title, 'Show Title on page?' %>
    <br />
    <%= f.label :layout %> <%= f.select :layout, application_layouts%>
    <%= f.label :uri, 'URI' %> <%= f.text_field :uri %><br />
  <% end %>
  
  <%= f.check_box :user_only%> <%= f.label :user_only, 'Only visible to logged-in users' %>
  <%= '<br />'.html_safe unless f.object.type == 'Rain::Cloud' %>
  <%= f.check_box :admin_only%> <%= f.label :admin_only, 'Only visible to admins' %><br />
  <%= f.cktext_area :content, :rows => 35, :cols => 76 %>
  <%= f.submit "Save", :id=>"edit_#{form.name}_submit" %>
<% end %>

app/views/rain/drops/edit.html.erb
<h4>Edit Text</h4>

<%= render :partial=>"rain/drops/form",:object=>@drop %>

app/views/rain/drops/new.html.erb
<h4>Create Text</h4>

<%= render :partial=>"rain/drops/form",:object=>@drop %>

app/views/rain/drops/update.js.erb
jQuery('#puddle .close').trigger('click');
jQuery('#puddle .contentWrap').html('');
<% unless request.env['HTTP_REFERER'].match(/\/rain\/admin\/drops$/) %>
  if (jQuery('.rain_drop.<%=@drop.id%>').size() == 0) {
    jQuery('.rain_drop').addClass('<%=@drop.id%>');
  }
  jQuery('.rain_drop.<%=@drop.id%>').effect('highlight',{},1500);
  jQuery('.rain_drop.<%=@drop.id%>').html('<%= escape_javascript(render @drop) %>');
  <% if @drop.class == Rain::Cloud %>
  if (window.location.pathname != '/' + '<%= @drop.uri %>') {
    window.location.pathname = '/' + '<%= @drop.uri %>';
  }
  <% end %>
  <% if @drop.show_title? %>
  else {
    window.location.reload(); <%# in case title has changed %>
  }
  <% end %>
<% end %>